# Site Settings
remote_theme: chrisrhymes/bulma-clean-theme

title: 다나와 기술블로그
email: cs@danawa.com
description: >
  다나와 기술블로그
# baseurl: "/"
# url: "https://danawalab.github.io"
# permalink: pretty
favicon: favicon.ico

paginate: 5
paginate_path: "/blog/page:num"



# plugins:
#   - jekyll-sitemap
#   - jekyll-paginate
#   - jekyll-feed
#   - jekyll-seo-tag
#   - kramdown
#   - rouge

# exclude: 
#   - Gemfile
#   - clean-theme.gemspec
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

livereload: true

# sass:
#   style: compressed
#   source_dir: _sass

# #google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "C.S. Rhymes"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true

# markdown: kramdown
# highlighter: rouge

# footer_menu: example_footer_menu

# collections:
#   products: 
#     output: true
#     layout: product
#     image: https://via.placeholder.com/800x600
#     show_sidebar: false